[package]
name = "zauber-compiler"

authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
thiserror = { version = "1" }
zauber-core = { path = "../zauber-core" }
zauber-parser = { path = "../zauber-parser" }
