[package]
name = "zauber-parser"

authors.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true
version.workspace = true

[dependencies]
bitflags = "2"
mime = "0.3"
nom = "7"
nom_locate = "4"
thiserror = { version = "1" }
